### ISSUE TITLE
Discussion of privacy issue mitigations for possible transferal of timestamps across contexts

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/hr-time#26]
#22 discusses a privacy issue of globalOffset being used for fingerprinting.
#25 is a another proposed way to transfer DomHighResolutionTimestamps between contexts

My question:

- How much more of a privacy issue is exposing global/local offset compared to code that creates its own Worker and then sends a time stamp across a few workers to figure out local offsets?

I guess.. my thinking is.. if the globalOffset time is based upon clock time in some way, there is no leak that is more significant than what is already leaked by correlating Date() to performance.now() in various contexts that can already be reached.

This leads me back to @bzbarsky and @sicking suggesting that perhaps everything should be based upon time... That makes it less finger printable because you'll have entire time zones with the same offSets. (@sicking seemd to be leaning that that way in #22 before we veered to performance.transferable() aka #25.)

**Comment by igrigorik** [comment]
For context, quoting from: https://github.com/w3c/hr-time/issues/22:

> We could simply add a performance.globalOffset property. This would return the timestamp of the "zero time" for the current global. That way translating to global time can simply be done by adding var globalTime = localTime + performance.globalOffset. And translating to local time is simply var localTime = globalTime - performance.globalOffset.

My main concern with this was due to exposing the same `globalOffset` as a pseudo-cookie:
 1. user navigates to site A, which contains a beacon that records globalOffset
 1. user navigates to site B, which contains a beacon that records globalOffset

If the globalOffset value is the same then the beacon can fingerprint the user based based on its value. That said, am I missing something here that would prevent this from happening? Also, note that we do want B to see same offset if B is iframed on A.

**Comment by toddreifsteck** [comment]
If globalOffset's base is NOT a "monotonic increasing number" but is instead based upon something not thumb printable such as UTC midnight Jan 1st, 2010 then I believe this eliminates the privacy concern as it removes the "only on this subsystem" piece of the algorithm. I'm spitballing a bit and there may be better ways to remove that.

**Comment by igrigorik** [comment]
@toddreifsteck it doesn't matter how the number is generated, as long as different sites get the same number it acts as a pseudo-cookie, no?

**Comment by toddreifsteck** [comment]
No. There would be no pseudo-cookie in the same way as Date.now() is not a pseudo-cookie. And the correlation of performance.now() and Date.now() is not a pseudo-cookie. Because the offset is simply used as a way to turn a performance.now() into a DOMHighResolutionTimeStamp that is relative to UTC, there is no stamp.

**Comment by toddreifsteck** [comment]
Unless I'm missing something, of course :-)

**Comment by igrigorik** [comment]
Hmm, think we're talking past each other. Perhaps we can take it up on our next call?

Date.now() is not a pseudo-cookie. A stable ~random number (regardless of how its generated) is.. which is what my understanding of performance.globalOffset is.

**Comment by sicking** [comment]
Date.now() is actually a bit of a psudo-cookie. The clock-offset between the server and the client can be measured and will remain constant until the user changes his clock. Thus it constitutes identifying information, like a cookie.

That said, you can only measure it pretty roughly. Both because date.now() is pretty coarse, and because you have to deal with the network delay when measuring difference between client and server.

It's possible that the `.globalOffset` proposal can be changed to include less private information than my original proposal. But a detailed proposal would be needed.

**Comment by igrigorik** [comment]
I believe we've addressed this in https://github.com/w3c/hr-time/issues/22#issuecomment-220085052 + followup posts. Closing, let's continue the discussion there.
