### ISSUE TITLE
Reducing the precision of the DOMHighResTimeStamp resolution

### ISSUE THREAD

**Issue by plehegar** [w3c/hr-time#56]
- [Fantastic Timers and Where to Find Them: High-Resolution Microarchitectural Attacks in JavaScript](https://gruss.cc/files/fantastictimers.pdf)
- [Firefox](https://blog.mozilla.org/security/2018/01/03/mitigations-landing-new-class-timing-attack/)
 decreased their resolution to 20us
- [Chrome](https://chromium-review.googlesource.com/c/chromium/src/+/849993) decreased theirs to 100us + 100us jitter for M64, M65 [Actions required to mitigate Speculative Side-Channel Attack techniques ](https://sites.google.com/a/chromium.org/dev/Home/chromium-security/ssca)
- [Safari](https://webkit.org/blog/8048/what-spectre-and-meltdown-mean-for-webkit/) is using 1ms, the same precision as Date.now().
- [Edge](https://blogs.windows.com/msedgedev/2018/01/03/speculative-execution-mitigations-microsoft-edge-internet-explorer/) decreased the resolution to 20us + 20us jitter

**Comment by siusin** [comment]
test -> https://w3c-test.org/hr-time/timing-attack.html

**Comment by toddreifsteck** [comment]
Per discussion on the 2/22 call, this issue is still in heavy flux. We will address this update when UAs come to consensus. When consensus occurs, we will update the CR.

@plehegar Could you add a note to the spec indicating that the current 5 us is likely to increase then follow it with a re-publish?

**Comment by mdrejhon** [comment]
I have serious grave concerns about permanent precision reductions.  

FireFox's 2ms precision now makes WebVR useless.

And a lot of 3D game programming techniques becomes impractical.

For a very good legitimate reason, I may have to begin automatically prompting users step by step instructions on overriding the precision reductions via advanced browser flags/config.  This reduces security, since I essentially have to tell users to reduce the security globally just for one site - I do not like this approach.

Better remedy is a prompt/permissions based API like fullscreen, camera, VR, etc.

Please urgently read:
https://bugzilla.mozilla.org/show_bug.cgi?id=1427918#c9

**Comment by mdrejhon** [comment]
Longer write-up:
-----------------------------------------
Firstly, Spectre and Meltdown are indeed extremely serious security issues.  
Many vendors, rightfully, doing emergency fixes including temporarily reducing timer precision.

However, I have seriously grave concerns about Mozilla/FireFox's decision to reduce performance.now() precision to 2ms -- there are unanticipated major side effects, including one that will reduce security.

MAJOR SIDE EFFECT #1:

The precision degradation is so massive (even at 60Hz) -- affecting fullscreen WebGL and WebVR majorly -- that I have heard from a friend that a site that plans to automatically detect the 2ms imprecision and automatically prompt the user with step-by-step instructions to fix the imprecision for their site.  As a global FireFox setting, this is problematic from a security perspective. A global setting changed.

I think the safer solution is:

"In an absolute emergency: Personally if there's a duress to reduce timer precision, then a temporary permissions API (cameras and fullscreen have more security/privacy fears) to prompt the user for permission to stay at 5us precision.  At least during the duration of security studying, until being reverted to maximized precision."

MAJOR SIDE EFFECT #2:

As a past game developer (most standards writers aren't game developers), let me tell you:

Accurate gametimes are necessary for accurate calculations of 3D object positions, especially in full-screen WebGL games.

At sub-refresh-cycles, animations should still use sub-millisecond accuracy to prevent jank, when calculating time-based animations (e.g. calculating object positions based on time) -- that's what 3D graphics often do compensating for fluctuating frame rates, they calculate object world positions based on gametime.   

That means 1000 inch per second moving balls (~60mph) can be wrongly mispositioned by 2 inches if the gametime is off by 2 millisecond.  That can mean goal/nogoal.  Fastballs, baseballs, hockey pucks can go much faster than this.  Low-precision gametimes will ruin a lot of HTML5 and WebGL game programming.

Gametimes need sub-millisecond accuracy, especially full-screen WebGL games, because they calculate real-world 3D object positions based on gametime.  

That way everything looks correct regardless of framerate. Framerates fluctuate all over the place, so video games using 3D graphics use gametime to calculate the position of everything.  3D object positions are calculated based on gametime.  Wrong gametime means everything janks like crazy in full screen WebGL games.

Again, this is for 60 Hz.  I'm not even talking about higher refresh rates.  1ms gametime errors create noticeable motion-fluidity flaws in 60Hz full-screen WebGL games!

Things even janks crazily with 5ms and 8ms gametime errors on a 60Hz display.  You're in the driver's seat of a 300mph car, in a racing game -- a 2ms gametime error becomes large even on a 60 Hz display.   Jank/jerkiness/stutter can get huge even at sub-refresh-cycle levels even on a 60 Hz display, even with sub-refresh-cycle errors.

Also, don't forget that there are advantages to frame rates above refresh rates in reducing latency: https://www.blurbusters.com/faq/benefits-of-frame-rate-above-refresh-rate/

My prediction is FireFox may get a tsunami wave of huge complaints from game designers suddenly hit by major precision reductions in ability to calculate gameworld positions.  

MAJOR SIDE EFFECT #3:

Depending on how timer precision is degraded, it potentially eliminates educational motion tests in web browsers.  Many scientific tests such as www.testufo.com/ghosting and www.testufo.com/frameskipping (display overclocking) is heavily dependant on perfect frame rate synchronization, and the site is able to detect whenever Chrome misses a frame.   

Peer reviewed papers have already been written based on browser motion tests (including www.blurbusters.com/motion-tests/pursuit-camera-paper ...) thanks to browser's ability to achieve perfect refresh rate synchronization)

Even one of my sites, TestUFO, depending on how the site is degraded in upcoming FireFox A/B tests (new versus old browser) -- it may be forced to do something similar to the popup in "MAJOR SIDE EFFECT #1" -- for specific kinds of peer-reviewed scientific motion testing.  Is there a way for me to tell users how to whitelist only one site (TestUFO.com) for high-precision timers, without doing it as a global setting?   (Thought exercise for W3C)

The TestUFO website already automatically displays a message telling TestUFO users to switch web browsers instead of IE/Edge for 120Hz testing, due to IE/Edge continued violation of Section 7.1.4.2 of HTML 5.2.  More than 50% of TestUFO visitors are using a refresh rate other than 60 Hz.

MAJOR SIDE EFFECT #4:

It makes WebVR useless.  

Its premise (without creating nausea/headaches) is heavily dependant on accurate gametimes for accurate positions of 3D objects (see MAJOR SIDE EFFECT #2 above).

MAJOR SIDE EFFECTS #5-100

I have a much longer list, but for brevity, I am shortening this email to point out the graveness of FireFox's decision.

CONCLUSION

The approach by the FireFox team should be refined.

If continued short-term emergency mitigation is absolute critical, it should includes a Permissions API (much like Full Screen mode and WebRTC camera permissions) to case-by-case ask the user for permission to use high-precision timers (allowing 5us or 1us precision).  

If absolutely necessary, this could even be limited to Organization Validation HTTPS sites, combined with only exclusive same-origin use, even triggered by a click, and only after confirming via a popup Permission API (like for WebRTC), that 5us/1us precision becomes granted to that particular site.

Long-term, these restrictions should be removed once the underlying causes of Spectre/Meltdown becomes solved.  However, massive precision reductions, that forces web developers to give instructions to visitors how to configure their web browsers, is a less secure solution.

Thanks,
Mark Rejhon
Founder, Blur Busters / TestUFO
(Past Invited Expert, W3C Web Platform Working Group for HTML 5.2)

**Comment by tdresser** [comment]
Just want to make sure I understand the concerns here. I don't think any browser vendors are reducing accuracy of timestamps passed to requestAnimationFrame, so we still have accurate frame timestamps.

I was under the impression that games would generally execute physics simulation using fixed time intervals: [this](https://gafferongames.com/post/fix_your_timestep/) comes to mind, though it may be quite out of date.

If this is the case, I don't see why you'd ever need a high accuracy timestamp other than for display time, which rAF gives you.

I suppose lack of accuracy in event timestamps could cause some issues, but that doesn't seem to be what you're referring to. Can you provide a bit more detail on why you need these timestamps?

**Comment by mdrejhon** [comment]
OK, that solves potentially one of the use cases.
However, it doesn't solve other use cases (e.g. WebVR)

The timestamps of input reads are important for calculating gametimes.  For example, input reads must be accurate as possible relative to gametimes.  And framerates fluctuates, so doing a performance.now concurrently with the input-read often results in better motionfeel for full-screen 3D graphics (OpenGL or WebVR).   

There are use cases where we definitely need an accurate VSYNC time with the rAF() but there are use cases where the timestamp of an input read needs to be as accurate as possible (preferably 100us rather than 1us).  The game designer should have that choice, and web standards creators should not dictate that choice.

**Comment by plehegar** [comment]
[for alignment, see also comment from Tobin at https://github.com/w3c/hr-time/pull/57#issuecomment-369332355]

**Comment by toddreifsteck** [comment]
Lets send a note to the privacy group after this is complete.

**Comment by yoavweiss** [comment]
Closing since the note has landed, but feel free to reopen if I'm missing something

**Comment by igrigorik** [comment]
FYI, recapping latest status:

- [Chrome](https://chromium-review.googlesource.com/c/chromium/src/+/849993) + [Edge](https://github.com/w3c/hr-time/pull/57#issuecomment-369332355): 100us + 100us jitter
- [Safari](https://trac.webkit.org/changeset/226495/webkit) + [Firefox](https://github.com/w3c/hr-time/issues/64#issuecomment-473371478): 1ms, same as Date.now()

**Comment by dakom** [comment]
So.. does this mean traditional game loops will be janky, no way around it?

I made a simple test based on mainloop.js here: https://github.com/dakom/mainloop-test

Gets a bit off in Chrome, in Firefox it's unbearable

**Comment by dakom** [comment]
So after learning a bit more about the issue it seems like maybe it's not an issue of the timing precision but rather some funkiness with the browser scheduling rAF callbacks?

I made a simpler straight delta+rAF test here: https://github.com/dakom/plainloop-test

Seems some people don't experience much jank, but it's clearer on Firefox, and I see lots of it (through running for like 30 secs)

**Comment by yoavweiss** [comment]
@dakom - Thanks for your comments. It seems your examples use either `Date.now()`-based timers or rAF. AFAICT, any jank you may experience in different implementations is not directly related to this issue.

**Comment by dakom** [comment]
thanks for taking a look @yoavweiss  - both are using rAF and the second is just straight delta using the DOMHighResTimeStamp that comes into the rAF callback.

But yeah - I guess it's an issue of vsync, frame-skipping, etc.? Will open an issue on the firefox list I guess

**Comment by asint** [comment]
Further to the excellent posts by blurbusters, I should also like to add a further situation, which is becoming more popular.

> I don't see why you'd ever need a high accuracy timestamp other than for display time

Please consider the ever increasing use of workers. It is now not entirely uncommon to calculate time dependant calculations in a separate thread where a value of rAF is not available.
I am currently working on a webVR project were calculating and compensating for latencies is quite honestly a bit of a nightmare. I think it is plainly obvious to envision these problems when considering workers.
